<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Assets\" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Assets\modmenu" />
      <EmbeddedResource Include="Assets\modmenu" />
      <None Remove="Assets\Cats\MonkyCar.jpg" />
      <EmbeddedResource Include="Assets\Cats\MonkyCar.jpg" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="0Harmony">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\0Harmony.dll</HintPath>
      </Reference>
      <Reference Include="Assembly-CSharp">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Assembly-CSharp.dll</HintPath>
      </Reference>
      <Reference Include="Assembly-CSharp-firstpass">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Assembly-CSharp-firstpass.dll</HintPath>
      </Reference>
      <Reference Include="CaputillaMelonLoader">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Caputilla.Melonloader.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppAssistantCoreSDKRuntime">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppAssistantCoreSDKRuntime.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppBakeryRuntimeAssembly">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppBakeryRuntimeAssembly.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppCebinae">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppCebinae.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppCinemachine">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppCinemachine.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppCyanilux.BlitRenderFeature">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppCyanilux.BlitRenderFeature.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppDissonanceVoip">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppDissonanceVoip.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppFacebook.Wit.Dictation">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppFacebook.Wit.Dictation.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppFusion.Addressables">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppFusion.Addressables.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppFusion.Common">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppFusion.Common.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppFusion.Realtime">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppFusion.Realtime.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppFusion.Runtime">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppFusion.Runtime.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppFusion.Sockets">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppFusion.Sockets.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppInterop.Common">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppInterop.Common.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppInterop.HarmonySupport">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppInterop.HarmonySupport.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppInterop.Runtime">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppInterop.Runtime.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppLIV.LCK">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppLIV.LCK.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppLIV.NativeAudioBridge">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppLIV.NativeAudioBridge.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppLMNL.QuestCam.Runtime">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppLMNL.QuestCam.Runtime.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppMeshBakerCore">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppMeshBakerCore.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppMeta.Voice.Hub.Runtime">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppMeta.Voice.Hub.Runtime.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppMeta.Voice.Samples.BuiltInTimer">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppMeta.Voice.Samples.BuiltInTimer.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppMeta.Voice.Samples.Chess">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppMeta.Voice.Samples.Chess.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppMeta.Voice.Samples.Dictation">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppMeta.Voice.Samples.Dictation.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppMeta.Voice.Samples.LightTraits">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppMeta.Voice.Samples.LightTraits.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppMeta.Voice.Samples.LiveUnderstanding">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppMeta.Voice.Samples.LiveUnderstanding.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppMeta.Voice.Samples.Shapes">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppMeta.Voice.Samples.Shapes.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppMeta.Voice.Samples.ShapesConduit">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppMeta.Voice.Samples.ShapesConduit.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppMeta.Voice.Samples.TTSVoices">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppMeta.Voice.Samples.TTSVoices.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppMeta.VoiceSDK.Mic.Common">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppMeta.VoiceSDK.Mic.Common.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppMeta.VoiceSDK.Mic.Other">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppMeta.VoiceSDK.Mic.Other.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppMeta.WitAi">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppMeta.WitAi.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppMeta.WitAi.Conduit">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppMeta.WitAi.Conduit.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppMeta.WitAi.Lib">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppMeta.WitAi.Lib.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppMeta.WitAi.TTS">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppMeta.WitAi.TTS.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppMeta.XR.BuildingBlocks">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppMeta.XR.BuildingBlocks.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppMirrorsAndReflections">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppMirrorsAndReflections.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppMono.Security">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppMono.Security.dll</HintPath>
      </Reference>
      <Reference Include="Il2Cppmscorlib">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2Cppmscorlib.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppNanoSockets">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppNanoSockets.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppNativeGallery">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppNativeGallery.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppNativeGallery.Runtime">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppNativeGallery.Runtime.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppNewtonsoft.Json">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppNewtonsoft.Json.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppOculus.AudioManager">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppOculus.AudioManager.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppOculus.Interaction">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppOculus.Interaction.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppOculus.Interaction.OVR">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppOculus.Interaction.OVR.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppOculus.Interaction.OVR.Samples">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppOculus.Interaction.OVR.Samples.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppOculus.LipSync">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppOculus.LipSync.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppOculus.Platform">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppOculus.Platform.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppOculus.Spatializer">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppOculus.Spatializer.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppOculus.VR">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppOculus.VR.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppPhoton3Unity3D">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppPhoton3Unity3D.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppPhotonChat">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppPhotonChat.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppPhotonRealtime">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppPhotonRealtime.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppPhotonUnityNetworking">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppPhotonUnityNetworking.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppPhotonUnityNetworking.Utilities">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppPhotonUnityNetworking.Utilities.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppPhotonVoice">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppPhotonVoice.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppPhotonVoice.API">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppPhotonVoice.API.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppPhotonVoice.Fusion">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppPhotonVoice.Fusion.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppPhotonVoice.PUN">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppPhotonVoice.PUN.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppPlayFab">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppPlayFab.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppSonicBloom.Koreo">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppSonicBloom.Koreo.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppSystem">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppSystem.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppSystem.Configuration">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppSystem.Configuration.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppSystem.Core">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppSystem.Core.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppSystem.Data">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppSystem.Data.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppSystem.Globalization">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppSystem.Globalization.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppSystem.Net.Http">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppSystem.Net.Http.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppSystem.Numerics">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppSystem.Numerics.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppSystem.Runtime.Serialization">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppSystem.Runtime.Serialization.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppSystem.Xml">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppSystem.Xml.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppSystem.Xml.Linq">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppSystem.Xml.Linq.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppTayx.Graphy">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppTayx.Graphy.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppVoiceSDK.Dictation.Runtime">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppVoiceSDK.Dictation.Runtime.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppVoiceSDK.Runtime">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2CppVoiceSDK.Runtime.dll</HintPath>
      </Reference>
      <Reference Include="Il2Cppwebsocket-sharp">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2Cppwebsocket-sharp.dll</HintPath>
      </Reference>
      <Reference Include="Il2Cpp__Generated">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Il2Cpp__Generated.dll</HintPath>
      </Reference>
      <Reference Include="MelonLoader">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\MelonLoader.dll</HintPath>
      </Reference>
      <Reference Include="Unity.Animation.Rigging">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Unity.Animation.Rigging.dll</HintPath>
      </Reference>
      <Reference Include="Unity.Burst">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Unity.Burst.dll</HintPath>
      </Reference>
      <Reference Include="Unity.InputSystem">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Unity.InputSystem.dll</HintPath>
      </Reference>
      <Reference Include="Unity.Mathematics">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Unity.Mathematics.dll</HintPath>
      </Reference>
      <Reference Include="Unity.PlayerPrefsEditor.Samples.SampleScene">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Unity.PlayerPrefsEditor.Samples.SampleScene.dll</HintPath>
      </Reference>
      <Reference Include="Unity.Postprocessing.Runtime">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Unity.Postprocessing.Runtime.dll</HintPath>
      </Reference>
      <Reference Include="Unity.ProBuilder">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Unity.ProBuilder.dll</HintPath>
      </Reference>
      <Reference Include="Unity.ProBuilder.KdTree">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Unity.ProBuilder.KdTree.dll</HintPath>
      </Reference>
      <Reference Include="Unity.ProBuilder.Poly2Tri">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Unity.ProBuilder.Poly2Tri.dll</HintPath>
      </Reference>
      <Reference Include="Unity.RenderPipeline.Universal.ShaderLibrary">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Unity.RenderPipeline.Universal.ShaderLibrary.dll</HintPath>
      </Reference>
      <Reference Include="Unity.RenderPipelines.Core.Runtime">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Unity.RenderPipelines.Core.Runtime.dll</HintPath>
      </Reference>
      <Reference Include="Unity.RenderPipelines.Universal.Runtime">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Unity.RenderPipelines.Universal.Runtime.dll</HintPath>
      </Reference>
      <Reference Include="Unity.TextMeshPro">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Unity.TextMeshPro.dll</HintPath>
      </Reference>
      <Reference Include="Unity.Timeline">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Unity.Timeline.dll</HintPath>
      </Reference>
      <Reference Include="Unity.VisualEffectGraph.Runtime">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Unity.VisualEffectGraph.Runtime.dll</HintPath>
      </Reference>
      <Reference Include="Unity.XR.ARCore">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Unity.XR.ARCore.dll</HintPath>
      </Reference>
      <Reference Include="Unity.XR.ARSubsystems">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Unity.XR.ARSubsystems.dll</HintPath>
      </Reference>
      <Reference Include="Unity.XR.CoreUtils">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Unity.XR.CoreUtils.dll</HintPath>
      </Reference>
      <Reference Include="Unity.XR.Interaction.Toolkit">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Unity.XR.Interaction.Toolkit.dll</HintPath>
      </Reference>
      <Reference Include="Unity.XR.Interaction.Toolkit.Samples.StarterAssets">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Unity.XR.Interaction.Toolkit.Samples.StarterAssets.dll</HintPath>
      </Reference>
      <Reference Include="Unity.XR.Management">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Unity.XR.Management.dll</HintPath>
      </Reference>
      <Reference Include="Unity.XR.Oculus">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Unity.XR.Oculus.dll</HintPath>
      </Reference>
      <Reference Include="Unity.XR.OpenXR">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Unity.XR.OpenXR.dll</HintPath>
      </Reference>
      <Reference Include="Unity.XR.OpenXR.Features.ConformanceAutomation">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Unity.XR.OpenXR.Features.ConformanceAutomation.dll</HintPath>
      </Reference>
      <Reference Include="Unity.XR.OpenXR.Features.MetaQuestSupport">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Unity.XR.OpenXR.Features.MetaQuestSupport.dll</HintPath>
      </Reference>
      <Reference Include="Unity.XR.OpenXR.Features.MockRuntime">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Unity.XR.OpenXR.Features.MockRuntime.dll</HintPath>
      </Reference>
      <Reference Include="Unity.XR.OpenXR.Features.OculusQuestSupport">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Unity.XR.OpenXR.Features.OculusQuestSupport.dll</HintPath>
      </Reference>
      <Reference Include="Unity.XR.OpenXR.Features.RuntimeDebugger">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\Unity.XR.OpenXR.Features.RuntimeDebugger.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.AccessibilityModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.AccessibilityModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.AIModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.AIModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.AndroidJNIModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.AndroidJNIModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.AnimationModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.AnimationModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ARModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.ARModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.AssetBundleModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.AssetBundleModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.AudioModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.AudioModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ClothModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.ClothModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ClusterInputModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.ClusterInputModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ClusterRendererModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.ClusterRendererModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.CoreModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.CoreModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.CrashReportingModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.CrashReportingModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.DirectorModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.DirectorModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.DSPGraphModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.DSPGraphModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.GameCenterModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.GameCenterModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.GIModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.GIModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.GridModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.GridModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.HotReloadModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.HotReloadModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ImageConversionModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.ImageConversionModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.IMGUIModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.IMGUIModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.InputLegacyModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.InputLegacyModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.InputModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.InputModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.JSONSerializeModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.JSONSerializeModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.LocalizationModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.LocalizationModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.NVIDIAModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.NVIDIAModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ParticleSystemModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.ParticleSystemModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.PerformanceReportingModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.PerformanceReportingModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.Physics2DModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.Physics2DModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.PhysicsModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.PhysicsModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ProfilerModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.ProfilerModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ScreenCaptureModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.ScreenCaptureModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.SharedInternalsModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.SharedInternalsModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.SpatialTracking">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.SpatialTracking.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.SpriteMaskModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.SpriteMaskModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.SpriteShapeModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.SpriteShapeModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.StreamingModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.StreamingModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.SubstanceModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.SubstanceModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.SubsystemsModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.SubsystemsModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TerrainModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.TerrainModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TerrainPhysicsModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.TerrainPhysicsModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TextCoreFontEngineModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.TextCoreFontEngineModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TextCoreTextEngineModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.TextCoreTextEngineModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TextRenderingModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.TextRenderingModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TilemapModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.TilemapModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TLSModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.TLSModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UI">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.UI.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UIElementsModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.UIElementsModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UIElementsNativeModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.UIElementsNativeModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UIModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.UIModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UmbraModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.UmbraModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UNETModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.UNETModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityAnalyticsCommonModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.UnityAnalyticsCommonModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityAnalyticsModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.UnityAnalyticsModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityConnectModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.UnityConnectModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityCurlModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.UnityCurlModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityTestProtocolModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.UnityTestProtocolModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityWebRequestAssetBundleModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.UnityWebRequestAssetBundleModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityWebRequestAudioModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.UnityWebRequestAudioModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityWebRequestModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.UnityWebRequestModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityWebRequestTextureModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.UnityWebRequestTextureModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityWebRequestWWWModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.UnityWebRequestWWWModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.VehiclesModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.VehiclesModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.VFXModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.VFXModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.VideoModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.VideoModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.VirtualTexturingModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.VirtualTexturingModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.VRModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.VRModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.WindModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.WindModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.XRModule">
        <HintPath>..\..\..\Downloads\Il2CppAssemblies\UnityEngine.XRModule.dll</HintPath>
      </Reference>
    </ItemGroup>
</Project>
